### ISSUE TITLE
Can get stuck in corners

### ISSUE THREAD

**Issue by Thonners** [steviet91/furmulaone_source#17]
If driving close to the wall, the car can get stuck in a corner, as when it resets it's aligned to the preceding segment's wall, so the only option is to drive into the wall again.

Should be fixed by resetting further away from the walls

**Comment by steviet91** [comment]
Could take a line normal to the collision line in the direction of the car and use this as an offset. We know which line we've collided with, is this with the updated collision rotation?

**Comment by steviet91** [comment]
Fixed using the new centreline
